# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c85733b1db204114511c8157167cca073275dc272a74ddc230a35b71076f8751349617dfc4b4b479045ea3be73e2efa1bce6eacba0cdd5844228841611b48466

test:
  secret_key_base: 99b8436d9a2d121372ed2f840373c5216c80d015e39b617357e7f79b1a091f78fb20d8484e5a5d43650fae3f5ef0b5b7d9f3342d623071027f1a3a22ab586d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
